### PR TITLE
RFC: metrics collection

### PR DESCRIPTION
**Pull request by denisdefreyne**
[rendered view](https://github.com/nanoc/rfcs/blob/metrics-collection/active/0000-metrics-collection.md)

### CODE REVIEW

**Comment by gpakosz** [comment]
My comments:

> **Which version of Nanoc do people use?**

I still use Nanoc `3.8` on may sites.

> **What operating systems is Nanoc used on?**

Will Bash for Windows count as Linux or Windows? (I bet it's going to be counted as Linux if you do nothing specific to detect it's Bash for Windows).

> **What Ruby versions is Nanoc run on?**

Indeed dropping Ruby `2.1` which is what Debian Jessie offers is a bit of a bummer. From there I switched to `ruby-install`, still... less straightforward as `sudo apt-get install ruby`. Also, don't forget some company policies may require only packages from stable. Decision depends on where Nanoc is used much.

> **How often are the legacy identifiers and/or patterns used?**

I didn't take the time to upgrade from Nanoc `3.8` to `4.x` on work projects (documentation sites). So I can't comment yet.

> *_How large are Nanoc sites? How long do they take to compile? *_

Some of my sites recompiled too often because of runtime data passed as filter parameters being captured in rules memory. AFAIR you improved the situation so I need to double check.

I believe it's important to have strong testing on outdatedness features because as soon as image optimizers, css and html minifiers enter the pipeline then compile times take a big hit.

> **Do people use the preprocessor? How long does the preprocessor take to run?**

I do use the preprocessor. To generate items on the fly or to inhibit items depending on configuration settings. I have various variables like `NANOC_TARGET` and `NANOC_ENV` that control behavior and now deprecated by the environments feature that landed recently.

I also plan to use the postprocessor on Nanoc `4.x`: e.g. brotli pass, ...

**Comment by gpakosz** [comment]
Oh this collection should be opt-in imho.

**Comment by majkinetor** [comment]
I propose few new:
- How many plugins people use (both official and custom) and custom ruby code. 
- How many custom commands.
- Proprortion of binary files vs textual.

**Comment by denisdefreyne** [comment]
> How many plugins people use (both official and custom) and custom ruby code.

Could you elaborate on what you’d want to use this metric for? (This metric is hard to quantify, I believe.)

> How many custom commands.

Same question as before: what would you use this metric for?

> Proprortion of binary files vs textual.

This would be interesting. Knowing how many items are binary gives us an idea of how asset management is used, especially when combined with compile times (also split up between textual and binary). I’ve added it to the RFC.

**Comment by denisdefreyne** [comment]
@gpakosz:

> I also plan to use the postprocessor on Nanoc 4.x: e.g. brotli pass, ...

A better use for this would be to have it as part of the normal Nanoc compilation process (e.g. `filter :brotli`).

> Oh this collection should be opt-in imho.

Agreed! I’ve clarified the RFC.

**Comment by denisdefreyne** [comment]
> Will Bash for Windows count as Linux or Windows?

Probably Linux, which I think is good enough because it effectively behaves as Linux anyway. I’m unsure how to detect bash for Windows otherwise.

**Comment by majkinetor** [comment]
> Same question as before: what would you use this metric for?

You want to know how much are specific features used in order to be able to better set priorities and plan for eventual feature removal etc.

**Comment by denisdefreyne** [comment]
@majkinetor Makes sense. I added this:

> **Which Nanoc commands are used, and how often?** Answering this question will give an idea of which commands are not useful, and might need to be removed or modified to make them useful. Knowing the number of non-builtin commands will give an idea of whether anything is missing from the base set of built-in commands.

**Comment by denisdefreyne** [comment]
Looking through the [atom/metrics package](https://github.com/atom/metrics), I noticed that they also report the exceptions that occur (just the name, i.e. no stack traces or paths). This could be quite useful to find out which errors that Nanoc users get the most.

**Comment by denisdefreyne** [comment]
Closing this, as I don’t think I’ll end up going forward with this. Minimal benefits,  complex implementation (especially when considering the privacy aspect), and nontrivial infrastructure needed.

**Pull request closed without merging**
