### PR TITLE
RFC: single-branch development

### PR DESCRIPTION
**Pull request by denisdefreyne**
[rendered view](https://github.com/nanoc/rfcs/blob/single-branch/active/0000-single-branch-development.md)

### CODE REVIEW

**Comment by majkinetor** [comment]
I like it as it will make you way more productive.

I also think the last drawback can drop out as you can create release notes in advance and mark some as unimplemented.

**Comment by majkinetor** [comment]
How do you plan to remove feature checks ones feature becomes released ? If you don't, a lot of the code will contain `if feature` that doesn't serve any purpose once released ? Do you plan to have something automatic as manual removal seems like waste of time.

**Comment by denisdefreyne** [comment]
To do: describe how the release process changes with this approach.

**Comment by denisdefreyne** [comment]
> How do you plan to remove feature checks ones feature becomes released?

The feature check would be removed entirely, rather than hardcoding it to be enabled.

I’d like to have an implementation where a Nanoc feature is defined for a certain minor (feature) version. When incrementing the Nanoc version number, the tests will fail for features that have not been enabled.

> Do you plan to have something automatic as manual removal seems like waste of time.

I believe manual removal will be quick enough; I don’t expect a feature check to happen in many places.

I’ve clarified the RFC with some of your questions.

**Comment by denisdefreyne** [comment]
This release process is now in effect!

**Pull request merged**
